---
name: Container
description: Builds, and optionally Pushes a Container
inputs:
  container:
    description: Container Name
    required: true
  token:
    description: GitHub Token with contents write permissions
    required: true
  push:
    description: GitHub Token with contents write permissions
    required: true
outputs:
  digest:
    description: Container Image Digest
    value: ${{ steps.image.outputs.digest }}
runs:
  using: "composite"
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --local user.email "${{ github.action }}+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git fetch --tags
        git pull || true

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: muhlba91
        password: ${{ inputs.token }}

    - name: Define Versions
      shell: bash
      run: |
        VERSION_FILE=`cat containers/NODE_RED_VERSION`
        echo "NODE_RED_VERSION=${VERSION_FILE%%*( )}" >> $GITHUB_ENV

    - name: Versioning and Changelog
      if: inputs.push == 'true'
      working-directory: containers/${{ inputs.container }}
      shell: bash
      run: |
        npx standard-version -i ../../release-CHANGELOG.md \
          --path ../../containers/${{ inputs.container }}** \
          --skip.commit \
          --skip.tag \
          --skip.bump
        npx standard-version \
          --path ../../containers/${{ inputs.container }}**

        TAG_NAME=`git describe --abbrev=0 --match "container/${{ inputs.container }}/v*"`
        echo "TAG_NAME=${TAG_NAME#"container/${{ inputs.container }}/v"}" >> $GITHUB_ENV

    - name: Push Git Tag
      if: inputs.push == 'true'
      shell: bash
      run: |
        git push --follow-tags origin ${{ github.ref_name }}

    - name: Build and Push Image
      id: image
      uses: docker/build-push-action@v4
      with:
        context: containers/${{ inputs.container }}
        platforms: linux/amd64
        push: ${{ inputs.push }}
        tags: |
          ghcr.io/muhlba91/${{ inputs.container }}:${{ env.NODE_RED_VERSION }}
          ghcr.io/muhlba91/${{ inputs.container }}:${{ env.NODE_RED_VERSION }}-${{ env.TAG_NAME }}
          ghcr.io/muhlba91/${{ inputs.container }}:${{ github.sha }}
        build-args: |
          NODE_RED_VERSION=${{ env.NODE_RED_VERSION }}
          CI_COMMIT_TIMESTAMP=${{ github.event.repository.updated_at }}
          CI_COMMIT_SHA=${{ github.sha }}
          CI_COMMIT_TAG=${{ env.TAG_NAME }}

    - name: GitHub Release
      if: inputs.push == 'true'
      uses: ncipollo/release-action@v1
      with:
        bodyFile: release-CHANGELOG.md
        name: container/${{ inputs.container }}/v${{ env.TAG_NAME }}
        tag: container/${{ inputs.container }}/v${{ env.TAG_NAME }}
        token: ${{ inputs.token }}
